service: logthread-backend

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  region: eu-north-1

functions:
  api:
    handler: app.backend.main.handler 
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements