service: logthread-backend

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  region: eu-north-1
  
  # Miljövariabler för din Lambda-funktion.
  # Dessa hämtas från GitHub Repository Secrets.
  environment:
    SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
    COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
    CLIENT_ID: ${{ secrets.CLIENT_ID }}
    USER_POOL_ID: ${{ secrets.USER_POOL_ID }}

  # Behörigheter för din Lambda-funktion.
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
          Resource: "arn:aws:dynamodb:eu-north-1:027625171538:table/Logs"

        - Effect: "Allow"
          Action: "sns:Publish"
          Resource: ${{ secrets.SNS_TOPIC_ARN }}

functions:
  api:
    handler: app.backend.main.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements